#!/bin/bash -e
# regenerate drupal6 mysql password

. /etc/default/inithooks

PASSWORD=$(mcookie)

CONF=/etc/drupal6/sites/default/dbconfig.php
sed -i "s/\$dbpass=\(.*\)/\$dbpass=\'$PASSWORD\';/" $CONF

CONF=/etc/dbconfig-common/drupal6.conf
sed -i "s/dbc_dbpass=\(.*\)/dbc_dbpass=\'$PASSWORD\'/" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user=drupal6 --pass="$PASSWORD"
